- name: Set permission of cron files
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  with_items:
    - {path: '/etc/anacrontab', mode: 600}
    - {path: '/etc/crontab', mode: 600}
    - {path: '/etc/cron.hourly', mode: 700}
    - {path: '/etc/cron.daily', mode: 700}
    - {path: '/etc/cron.weekly', mode: 700}
    - {path: '/etc/cron.monthly', mode: 700}
    - {path: '/etc/cron.d', mode: 700}
    - {path: '/var/spool/cron', mode: 700}

- name: Remove cron and at deny file
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/cron.deny
    - /etc/at.deny

- name: Allow only root user for cron and at
  copy:
    dest: "{{ item }}"
    content: "root"
  with_items:
    - /etc/cron.allow
    - /etc/at.allow
