- name: Set permission of ssh files
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  with_items:
    - {path: '/etc/ssh/sshd_config', mode: 640}

- lineinfile: dest=/etc/ssh/sshd_config regexp="{{ item.regex }}" line="{{ item.line }}"
  with_items:
    - { regex: "^#?Protocol ", line: "Protocol 2" }
    - { regex: "^#?LogLevel ", line: "LogLevel INFO" }
    - { regex: "^#?MaxAuthTries ", line: "MaxAuthTries 4" }
    - { regex: "^#?IgnoreRhosts ", line: "IgnoreRhosts yes" }
    - { regex: "^#?HostbasedAuthentication ", line: "HostbasedAuthentication no" }
    - { regex: "^#?PermitEmptyPasswords ", line: "PermitEmptyPasswords no" }
    - { regex: "^#?PermitUserEnvironment ", line: "PermitUserEnvironment no" }
    - { regex: "^#?Ciphers ", line: "Ciphers aes256-ctr,aes192-ctr,aes128-ctr" }
    - { regex: "^#?Banner ", line: "Banner /etc/issue" }
  register: line

- service: name=sshd state=reloaded
  when: line.changed
