- name: The password security policy must be enforced login.defs
  lineinfile:
    dest: /etc/login.defs
    line: "{{ item.line }}"
    regexp: "{{ item.regex }}"
  with_items:
    - { regex: "^PASS_MIN_LEN.*", line: "PASS_MIN_LEN 10" }
    - { regex: "^PASS_MAX_DAY.*", line: "PASS_MAX_DAYS 90" }
    - { regex: "^PASS_MIN_DAYS.*", line: "PASS_MIN_DAYS 7" }
    - { regex: "^PASS_WARN_AGE.*", line: "PASS_WARN_AGE 7" }



- name: Add trap in /etc/profile
  lineinfile:
    dest: /etc/profile
    line: "{{ item.line }}"
    regexp: "{{ item.regex }}"
    insertafter: "^# /etc/profile$"
  with_items:
    - { regex: "^trap ", line: "trap 1 3 9 15" }

- name: Update the /etc/profile
  lineinfile:
    dest: /etc/profile
    line: "{{ item.line }}"
    regexp: "{{ item.regex }}"
  with_items:
    - { regex: "^ulimit -S$", line: "ulimit -S" }
